# File: .github/workflows/workflow.yml

on: 
  workflow_dispatch:

name: infra

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: debug secrets
      run: |
        echo "secrets.RG=<${{ secrets.RG }}>"                | sed -r 's/(.)/\1 /g'
        echo "secrets.ASP=<${{ secrets.ASP }}>"               | sed -r 's/(.)/\1 /g'
        echo "secrets.WEBAPP=<${{ secrets.WEBAPP }}>"            | sed -r 's/(.)/\1 /g'
        echo "secrets.LOC=<${{ secrets.LOC }}>"               | sed -r 's/(.)/\1 /g'
        echo "secrets.AZURE_CREDENTIALS=<${{ secrets.AZURE_CREDENTIALS }}>" | sed -r 's/(.)/\1 /g'
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "az appservice plan create -g ${{ secrets.RG }} -n ${{ secrets.ASP }} --is-linux --number-of-workers 1 --sku B1 --location ${{ secrets.LOC }}"
          az appservice plan create -g ${{ secrets.RG }} -n ${{ secrets.ASP }} --is-linux --number-of-workers 1 --sku B1 --location ${{ secrets.LOC }}
          echo "az webapp create -g ${{ secrets.RG }} -p ${{ secrets.ASP }} -n ${{ secrets.WEBAPP }}  --runtime node:20-lts"
          az webapp create -g ${{ secrets.RG }} -p ${{ secrets.ASP }} -n "${{ secrets.WEBAPP }}"  --runtime "node:20-lts"
